services:
  maelstrom:
    build:
      context: .
    volumes:
    - type: volume
      source: store
      target: /maelstrom/store
    command: ./maelstrom serve
    ports:
    - 8080:8080
volumes:
  store: