services:
  cli:
    build:
      context: .
    volumes:
    - type: volume
      source: store
      target: /maelstrom/store
    command: tail -f /dev/null
  server:
    build:
      context: .
    volumes:
    - type: volume
      source: store
      target: /maelstrom/store
    command: ./maelstrom serve
volumes:
  store: