services:
  cli:
    build:
      context: .
    volumes:
    - store:/maelstrom/store
    command: tail -f /dev/null
  server:
    build:
      context: .
    volumes:
    - store:/maelstrom/store
    command: ./maelstrom serve
volumes:
  store: